chatbot_api_entities.chatbot_api_entities_collection.*:
  type: config_entity
  label: 'Entity collection'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    entity_type:
      type: string
      label: 'Entity Type ID'
    bundle:
      type: string
      label: 'Bundle'
    synonyms:
      type: string
      label: 'Synonyms'
    query_handlers:
      type: sequence
      label: 'Enabled query handlers'
      sequence:
        type: chatbot_api_entities_query_handler
    push_handlers:
      type: sequence
      label: 'Enabled push handlers'
      sequence:
        type: chatbot_api_entities_push_handler

chatbot_api_entities_push_handler:
  type: mapping
  label: 'Push handler'
  mapping:
    id:
      type: string
      label: 'ID'
    provider:
      type: string
      label: 'Provider'
    settings:
      type: chatbot_api_entities_push_handler_settings.[%parent.id]

chatbot_api_entities_push_handler_settings.*:
  type: sequence
  label: 'Push settings'
  sequence:
    type: string
    label: 'Value'

chatbot_api_entities_query_handler:
  type: mapping
  label: 'Query handler'
  mapping:
    id:
      type: string
      label: 'ID'
    provider:
      type: string
      label: 'Provider'
    settings:
      type: chatbot_api_entities_query_handler_settings.[%parent.id]

chatbot_api_entities_query_handler_settings.*:
  type: sequence
  label: 'Query settings'
  sequence:
    type: string
    label: 'Value'
